[package]
name = "ef-testing"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { workspace = true }

# Eth deps
ef-tests = { workspace = true }
reth-primitives = { workspace = true }
revm-primitives = { workspace = true }
reth-rlp = { workspace = true }

# Kakarot deps
kakarot-rpc-core = { workspace = true }
hive-utils = { workspace = true }

# Starknet deps
dojo-test-utils = { workspace = true }
katana-core = { workspace = true }
starknet_api = { workspace = true }
starknet = { workspace = true }

# Other
async-trait = { workspace = true }
ctor = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace= true } 
rstest = { workspace= true } 
tokio = { workspace = true }
tracing = "0.1.37"
walkdir = { workspace = true }

[dev-dependencies]
tracing-subscriber = "0.3.17"

[features]
ef-tests = []
