name: try

on:
  workflow_call: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: output
        run: |
          echo "message1=hello world 1" >> $GITHUB_OUTPUT
          echo "message2=hello world 2" >> $GITHUB_OUTPUT
          echo "message3=hello world 3" >> $GITHUB_OUTPUT
          echo "message4=hello world 4" >> $GITHUB_OUTPUT
        id: run_output
      - name: print-output
        run: echo "${{join(steps.run_output.outputs.*, '\n')}}"
      - name: post-process
        run: python scripts/test_script.py
        env:
          OUTPUT: ${{join(steps.run_output.outputs.*, '\n')}}
