name: test

on:
  workflow_call:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - name: Load compiled kakarot contracts
        id: cached-contracts
        uses: actions/cache/restore@v3
        with:
          path: ./lib/kakarot/build
          key: ${{ runner.os }}-contracts
      - name: Setup rust env
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: llvm-tools-preview
          override: true
      - name: Retrieve cached dependencies
        uses: Swatinem/rust-cache@v2
      # fetch ef tests
      - name: fetch ef tests
        run: make setup
      # fetch dump
      - name: fetch dump
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make fetch-dump
      - uses: taiki-e/install-action@nextest
      # run tests
      - name: run tests
        run: make ef-tests
