name: test

on:
  workflow_call: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test:
    # trunk-ignore(actionlint/runner-label)
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - name: Load compiled kakarot contracts
        id: cached-contracts
        uses: actions/cache/restore@v3
        with:
          path: ./lib/kakarot/build
          key: ${{ runner.os }}-contracts
      - name: Setup rust env
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: llvm-tools-preview
          override: true
      - name: Retrieve cached dependencies
        uses: Swatinem/rust-cache@v2
      - name: fetch ef tests
        run: make setup
      - name: fetch dump
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} make fetch-dump
      - uses: taiki-e/install-action@nextest
      - name: run tests
        run: make ef-tests
