name: test

on:
  workflow_call: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test:
    # trunk-ignore(actionlint/runner-label)
    runs-on: ubuntu-latest-32-cores
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Setup rust env
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: llvm-tools-preview
          override: true
      - name: Retrieve cached dependencies
        uses: Swatinem/rust-cache@v2
      - name: fetch ef tests
        run: make setup
      - name: fetch Kakarot
        run: make setup-kakarot
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: taiki-e/install-action@nextest
      - name: run tests
        run: |
          output=$(make tests 2>&1)
          exit_code=$?
          echo "$output"
          if [ $exit_code -ne 0 ]; then
            exit $exit_code
          fi
          output_base64=$(echo "$output" | base64 -w 0)
          echo "test-output=$output_base64" >> $GITHUB_OUTPUT
        id: run_tests
      - name: get resources
        run: python scripts/compute_resources.py
        env:
          OUTPUT: ${{ steps.run_tests.outputs.test-output }}
      # upload artifacts
      - name: upload resources
        uses: actions/upload-artifact@v3
        with:
          path: ./resources.csv
          name: resources-usage
